import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { createRequire } from 'node:module';
import { build } from 'esbuild';
import sharp from 'sharp';
import jsQR from 'jsqr';
import { createOrbMotion, stepOrbMotion, fluidOutline, waveEnvelope } from '../docs/app/orb-motion.js';
const require=createRequire(import.meta.url);
const {outputFiles}=await build({entryPoints:['src/components/QrCode.tsx'],bundle:true,write:false,platform:'node',format:'cjs',jsx:'automatic',external:['react']});
const module={exports:{}};
new Function('require','module','exports',outputFiles[0].text)(require,module,module.exports);
const React=require('react'), {renderToStaticMarkup}=require('react-dom/server');
const token='0123456789abcdef0123456789abcdef';
const direct=`https://a-long-temporary-tunnel.trycloudflare.com/${token}/`;
const pairing=`https://nova-izuki.github.io/izuki/app/#pc=${encodeURIComponent(direct)}`;
for(const text of [direct,pairing]) {
  const svg=renderToStaticMarkup(React.createElement(module.exports.QrCode,{text,label:'Test QR'}));
  assert(svg.includes('flex-shrink:0'),'QR must not collapse in a flex row');
  const {data,info}=await sharp(Buffer.from(svg)).ensureAlpha().raw().toBuffer({resolveWithObject:true});
  assert.equal(jsQR(new Uint8ClampedArray(data),info.width,info.height)?.data,text,'actual rendered QR failed to decode');
  assert(info.width>=200);
}
const state=createOrbMotion();
for(let i=0;i<120;i++)stepOrbMotion(state,1/60,i%30<8?.95:0,'speaking');
assert(state.blobs.every(b=>Number.isFinite(b.x)&&Math.abs(b.x)<.5));
const rings=fluidOutline(state.blobs,72);assert(rings.length>0&&rings.every(r=>r.length>3));
for(let i=0;i<240;i++)stepOrbMotion(state,1/60,0,'idle');
assert(state.energy<.0001,'fluid must settle between/after speech');
stepOrbMotion(state,NaN,NaN,'speaking',Infinity);assert(Number.isFinite(state.time));
const times=[];for(let i=0;i<30;i++){const t=performance.now();fluidOutline(state.blobs,72);times.push(performance.now()-t);}times.sort((a,b)=>a-b);
console.log(`Fluid geometry p95: ${times[28].toFixed(2)} ms (this test machine, not a device-wide FPS guarantee)`);
const wav=new ArrayBuffer(44+16000*2), v=new DataView(wav), word=(at,s)=>[...s].forEach((c,i)=>v.setUint8(at+i,c.charCodeAt(0)));
word(0,'RIFF');v.setUint32(4,wav.byteLength-8,true);word(8,'WAVE');word(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,16000,true);v.setUint32(28,32000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);word(36,'data');v.setUint32(40,32000,true);
for(let i=0;i<8000;i++)v.setInt16(44+i*2,Math.sin(i*.2)*12000,true);
const envelope=waveEnvelope(wav);assert(envelope.levels[4]>.5);assert.equal(envelope.levels[40],0);assert.equal(waveEnvelope(new ArrayBuffer(12)),null);
let requests=[];let response={ok:true,status:200,json:async()=>({ok:true,service:'izuki',version:'test'})};
const context={window:{},URL,URLSearchParams,AbortController,setTimeout,clearTimeout,fetch:async(url,options)=>{requests.push({url,options});return response;}};
vm.runInNewContext(fs.readFileSync('docs/app/pairing.js','utf8'),context);
const p=context.window.IzukiPairing;
assert.equal(p.parse(pairing),direct);assert.equal(p.parse(direct),direct);
for(const bad of ['javascript:alert(1)','https://example.com/','https://user:pass@example.com/'+token,'https://example.com/'+token+'?secret=1'])assert.equal(p.parse(bad),null);
assert.equal((await p.check(pairing)).version,'test');assert(requests.every(r=>!r.options.method||r.options.method==='GET'));
response={ok:true,status:200,json:async()=>({welcome:'not izuki'})};await assert.rejects(()=>p.check(direct),/no longer reaches/);
response={ok:false,status:401,json:async()=>({error:'expired'})};await assert.rejects(()=>p.check(direct),/no longer reaches/);
context.fetch=async(url,options)=>{requests.push({url,options});return url.endsWith('/health')?{ok:false,status:404,json:async()=>({})}:{ok:true,status:200,json:async()=>({hear:true})};};
assert.equal((await p.check(direct)).version,'older PC build','previous release remains pairable');
context.fetch=async()=>{const error=new Error('timed out');error.name='AbortError';throw error;};
await assert.rejects(()=>p.check(direct),/8 seconds/);
console.log('Rendered QR decoding, strict pairing links, read-only health checks, fluid stability and real WAV envelopes pass.');
